### ISSUE TITLE
sale not created

### ISSUE THREAD

**Issue by REGENTUM** [Javdu10/Plugin-NowPayments#1]
I received payment, the money was credited, but the sale was not created in the shop plugin panel

**Comment by Javdu10** [comment]
> I received payment, the money was credited, but the sale was not created in the shop plugin panel

Hello @REGENTUM I did not see the issue sorry, without further information there is nothing I can do. You mostly had something like cloudflare misconfigured in-between that blocked the payment. Let me know if you have an error log
